# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/WeatherChecker.sln
    - name: Build
      run: dotnet build ./src/WeatherChecker.sln --no-restore
    - name: Test
      run: dotnet test ./src/WeatherChecker.Test/WeatherChecker.Test.csproj --no-build --verbosity normal --logger "trx;LogFileName=xtests.trx"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        trx_files: "/home/runner/work/WeatherChecker/WeatherChecker/src/WeatherChecker.Test/TestResults/xtests.trx"
